apiVersion: v1
kind: Pod
metadata:
  name: azure-to-aws-s3-connect-from-aks-pod
  namespace: default
  labels:
    azure.workload.identity/use: "true" # Required for workload identity
spec:
  serviceAccountName: azure-to-aws-s3-connect-from-aks-pod-sa
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["sleep"]
      # command: ["sh", "-c", "aws sts get-caller-identity && sleep 604800"]
      args: ["604800"]
      env:
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::931359510199:role/test-azure-aws-s3role" # Replace with your actual AWS Role ARN
          # Replace AWS_ACCOUNT_ID with your actual AWS account ID
          # Replace AWS Role ARN this with your actual role ARN that has permissions to access S3
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: "/var/run/secrets/azure/tokens/azure-identity-token"
      volumeMounts:
        - name: azure-identity-token
          mountPath: /var/run/secrets/azure/tokens
          readOnly: true
  volumes:
    - name: azure-identity-token
      projected:
        sources:
          - serviceAccountToken:
              audience: "sts.amazonaws.com"
              expirationSeconds: 3600
              path: azure-identity-token
