apiVersion: v1
kind: Pod
metadata:
  name: aks-pod-to-s3-access
  namespace: default
  labels:
    azure.workload.identity/use: "true" # Required for workload identity
spec:
  serviceAccountName: azure-access-managed-identity-sa
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["sh", "-c", "aws sts get-caller-identity && sleep 604800"]
      env:
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::931359510199:role/Azure_AWS_S3_Access" # <-- Replace this
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: "/var/run/secrets/azure/tokens/azure-identity-token"
      volumeMounts:
        - name: azure-identity-token
          mountPath: /var/run/secrets/azure/tokens
          readOnly: true
  volumes:
    - name: azure-identity-token
      projected:
        sources:
          - serviceAccountToken:
              audience: api://AzureADTokenExchange
              expirationSeconds: 3600
              path: azure-identity-token
