apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-cli-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: az-cli-deployment
  template:
    metadata:
      labels:
        app: az-cli-deployment
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: azure-access-managed-identity-sa
      containers:
        - name: azcli
          image: mcr.microsoft.com/azure-cli
          command: ["sleep"]
          args: ["3600"]
