# This YAML file defines a Kubernetes Pod that uses a managed identity to access Azure Blob Storage.
---
apiVersion: v1
kind: Pod
metadata:
  name: python-aks-blob-pod
  namespace: default
  labels:
    azure.workload.identity/use: "true" # Required. Only pods with this label can use workload identity.
spec:
  serviceAccountName: azure-access-managed-identity-sa # This binds the pod to the MI
  containers:
    - name: python-blob-container
      image: prasadreddy2349/aks-python-azure-blob-reader
      imagePullPolicy: Always
      env:
        - name: AZURE_STORAGE_ACCOUNT_NAME
          value: demoakstgacc123 # Replace with your Azure Storage Account name
        - name: AZURE_STORAGE_CONTAINER_NAME
          value: test-container # Replace with your Azure Storage Container name
      resources: # Optional resource requests and limits
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"
