# This file defines a Kubernetes ServiceAccount that uses Azure Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-access-managed-identity-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: 24a568b2-d4c8-4fc8-9ee1-3b099ea75fea # Replace with your Azure Managed Identity client ID
    # azure.workload.identity/tenant-id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Replace with your Azure tenant ID
